arg python_version=3.6
from python:$python_version
arg python_version

copy . /var/app/pin

workdir /var/app/pin/pin
run pip install -r ../requirements.txt

env PYTHONPATH=/var/app/pin PIN_DB_CONF=/var/app/pin/pin/tests/pin.conf
cmd ["sh", "-c", "python -m pytest tests/ && tail -f /dev/null"]
