ARG centos_version=8
FROM centos:$centos_version as builder
# needed to do again after FROM due to docker limitation
ARG centos_version

# install dependencies
run yum install -y gcc gcc-c++\
    make \
    openssl-devel \
    pcre-devel \
    zlib-devel \
    python3-devel \
    && yum clean all

workdir /var/engine/nginx
